package aston.team15.jumazy.view;

public enum Screens {

	MAIN_MENU_SCREEN, START_GAME_SCREEN, TUTORIAL_SCREEN, TEXTURE_SELECTION_SCREEN, 
	PLAYER_NUMBER_SELECTION_SCREEN, SETTINGS_SCREEN, GAME_SCREEN

}
